version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    container_name: ms-nginxQ
    tty: true
    depends_on:
      - node
    ports:
      - 8000:80
    links:
      - node
      - vue

  node:
    build:
      context: .
      dockerfile: docker/node.Dockerfile
    container_name: ms-nodeQ
    tty: true
    restart: always
    volumes:
      - ./services/node:/var/www/node

  vue:
    build:
      context: .
      dockerfile: docker/vue.Dockerfile
    container_name: ms-vueQ
    tty: true
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5050:8080"
    volumes:
      - ./services/vue:/var/www/vue
